[project]
name = "amazon-captcha-handler"
version = "0.1.0"
description = "Amazon captcha handler"
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "pillow>=11.2.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
