name: Build and publish to github release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v5

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: setup environment
        run: uv sync

      - name: build wheel
        run: uv build

      - name: upload release
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          files: dist/*
          tag_name: ${{ github.ref_name }}
